import HomepageSearch from '@/components/HomepageSearch/HomepageSearch'
import HomepageSlideOptions from '@/components/HomepageSlideOptions/HomepageSlideOptions'
import HomepageTrailers from '@/components/HomepageTrailers/HomepageTrailers'
import ModalVideo from '@/components/ModalVideo/ModalVideo'
import { RootState } from '@/store/store'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { useSelector } from 'react-redux'


export interface MovieList {
  adult: boolean,
  backdrop_path: string,
  genres_ids: Number[],
  id: number,
  original_languege: string,
  original_title : string,
  original_name  : string,
  overview: string,
  popularity: number,
  poster_path: string,
  release_date : string,
  first_air_date : string, 
  title: string,
  video: boolean,
  vote_average: number,
  vote_count: number,
  media_type : string
}

interface dataProps {
  dataMovieList: MovieList[]
}


export default function Home({ dataMovieList }: dataProps) {

  const modalTrailers = useSelector<RootState>(state => state.movieSlice.isModalTrailers)

  const firstSlideOptions = [{
    name: 'Today',
    id: 'day'
  }, {
    name: 'This week',
    id: 'week'
  }]


  const secondSlideOptions = [{
    name: 'On TV',
    id: 'tv'
  }, {
    name: 'In Theaters',
    id: 'movie'
  }]
  
  return (
    <>
      <Head>
        <title>The Movie Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {dataMovieList.length > 0 && <HomepageSearch backgroundImage={dataMovieList[Math.floor(dataMovieList.length * Math.random())].backdrop_path} />}
      <HomepageSlideOptions type='trending' options={firstSlideOptions} title={'Trending'} />
      <HomepageTrailers />
      <HomepageSlideOptions type='popular' options={secondSlideOptions} title={"What's Popular"} />

      {modalTrailers && <ModalVideo />}
    </>
  )
}

export const getStaticProps: GetStaticProps<dataProps> = async () => {
  try {
    const result = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL_MOVIEDB}/movie/popular?api_key=${process.env.NEXT_PUBLIC_MOVIE_API_KEY}&language=en-US&page=${1}`)
    const data = await result.json()
    console.log(data)
    return {
      props: {
        dataMovieList: data.results
      }
    }
  } catch (err) {
    return {
      props: {
        dataMovieList: []
      }
    }
  }
}
